### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by timja** [jenkins-infra/incrementals-publisher#11]
If permissions aren't set up property an undefined object is accessed

```
{"message":"FailRequestError: Invalid archive retrieved from Jenkins, perhaps the plugin is not properly incrementalized?\nNo applicable permissions for jenkinsci/lib-access-modifier from https://ci.jenkins.io/job/jenkinsci-libraries/job/lib-access-modifier/job/PR-40/2/artifact/**/*.5401eca976ec/*.5401eca976ec*/*zip*/archive.zip\n    at IncrementalsPlugin.main (/usr/src/app/IncrementalsPlugin.js:218:13)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error"}
{"meta":{"req":{"url":"/","headers":{"host":"incrementals.jenkins.io","x-request-id":"32a63bc9ee2d9c22d09142cd4d45cc02","x-real-ip":"13.58.192.76","x-forwarded-for":"13.58.192.76","x-forwarded-proto":"https","x-forwarded-host":"incrementals.jenkins.io","x-forwarded-port":"443","x-scheme":"https","content-length":"98","user-agent":"curl/7.58.0","accept":"*/*","authorization":"Bearer HbafY468e3zvejNQhYQsIBadnpPUSfHoUSPyxO690gHTtOcIDbkYbw==","content-type":"application/json"},"method":"POST","httpVersion":"1.1","originalUrl":"/","query":{}},"res":{"statusCode":400},"responseTime":1004},"level":"info","message":"HTTP POST /"}
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at StreamZip.<anonymous> (/usr/src/app/lib/permissions.js:29:31)
    at StreamZip.emit (events.js:315:20)
    at StreamZip.emit (/usr/src/app/node_modules/node-stream-zip/node_stream_zip.js:598:33)
    at FsRead.readEntriesCallback [as callback] (/usr/src/app/node_modules/node-stream-zip/node_stream_zip.js:345:22)
    at FsRead.readCallback (/usr/src/app/node_modules/node-stream-zip/node_stream_zip.js:869:21)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
```

**Comment by timja** [comment]
Specifically happens if the github repo is wrong...
